# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run tests on commit and PR to master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-jvm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew jvmTest
      - name: Run kotlin JVM tests
        run: ./gradlew jvmTest
      - name: Run kotlin JS tests
        run: ./gradlew jsTest
